FROM google/cloud-sdk:274.0.1-alpine

LABEL image='foo0x29a/cloud-sdk'
LABEL tag='274.0.1-alpine'
LABEL ref='https://github.com/foo0x29a/dockerfiles'

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]